### ISSUE TITLE
Request instance with price 0 fails

### ISSUE THREAD

**Issue by kmidkiff** [service-bot/servicebot#201]
{"error":{"type":"StripeInvalidRequestError","stack":"Error: Invalid integer: \n    at Constructor._Error (/Users/kmidkiff/WebstormProjects/servicebot/node_modules/stripe/lib/Error.js:12:17)\n    at Constructor (/Users/kmidkiff/WebstormProjects/servicebot/node_modules/stripe/lib/utils.js:102:13)\n    at Constructor (/Users/kmidkiff/WebstormProjects/servicebot/node_modules/stripe/lib/utils.js:102:13)\n    at Function.StripeError.generate (/Users/kmidkiff/WebstormProjects/servicebot/node_modules/stripe/lib/Error.js:57:14)\n    at IncomingMessage.<anonymous> (/Users/kmidkiff/WebstormProjects/servicebot/node_modules/stripe/lib/StripeResource.js:172:39)\n    at emitNone (events.js:110:20)\n    at IncomingMessage.emit (events.js:207:7)\n    at endReadableNT (_stream_readable.js:1059:12)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","rawType":"invalid_request_error","param":"amount","message":"Invalid integer: ","raw":{"type":"invalid_request_error","message":"Invalid integer: ","param":"amount","headers":{"server":"nginx","date":"Fri, 06 Oct 2017 21:17:54 GMT","content-type":"application/json","content-length":"116","connection":"close","access-control-allow-credentials":"true","access-control-allow-methods":"GET, POST, HEAD, OPTIONS, DELETE","access-control-allow-origin":"*","access-control-expose-headers":"X-Stripe-Privileged-Session-Required,stripe-manage-version,X-Stripe-External-Auth-Required","access-control-max-age":"300","cache-control":"no-cache, no-store","request-id":"req_9OGiPoCaEwNdN6","stripe-version":"2017-02-14"},"statusCode":400,"requestId":"req_9OGiPoCaEwNdN6"},"headers":{"server":"nginx","date":"Fri, 06 Oct 2017 21:17:54 GMT","content-type":"application/json","content-length":"116","connection":"close","access-control-allow-credentials":"true","access-control-allow-methods":"GET, POST, HEAD, OPTIONS, DELETE","access-control-allow-origin":"*","access-control-expose-headers":"X-Stripe-Privileged-Session-Required,stripe-manage-version,X-Stripe-External-Auth-Required","access-control-max-age":"300","cache-control":"no-cache, no-store","request-id":"req_9OGiPoCaEwNdN6","stripe-version":"2017-02-14"},"requestId":"req_9OGiPoCaEwNdN6","statusCode":400}}

**Comment by kmidkiff** [comment]
amount was null, need to change default val
