### ISSUE TITLE
Unknown error server side

### ISSUE THREAD

**Issue by kmidkiff** [service-bot/servicebot#263]
{ Error: Not Found
Valid Request!
    at /Users/kmidkiff/WebstormProjects/servicebot/plugins/api-gateway/app.js:185:23
permission for /service-instances/:id/add-charge is post_service_instances_id_add_charge
    at Layer.handle [as handle_request] (/Users/kmidkiff/WebstormProjects/servicebot/node_modules/express/lib/router/layer.js:95:5)
userName: kevin@servicebot.io has permission: post_service_instances_id_add_charge. Ability to make api call: true
    at trim_prefix (/Users/kmidkiff/WebstormProjects/servicebot/node_modules/express/lib/router/index.js:317:13)
    at /Users/kmidkiff/WebstormProjects/servicebot/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/kmidkiff/WebstormProjects/servicebot/node_modules/express/lib/router/index.js:335:12)
    at Immediate.next (/Users/kmidkiff/WebstormProjects/servicebot/node_modules/express/lib/router/index.js:275:10)
POST /api/v1/service-instances/3/add-charge     at Immediate.<anonymous> (/Users/kmidkiff/WebstormProjects/servicebot/node_modules/express/lib/router/index.js:635:15)
404     at runCallback (timers.js:783:20)
48.432 ms - 172    at tryOnImmediate (timers.js:743:5)

    at processImmediate [as _immediateCallback] (timers.js:714:5) status: 404 }
Error: Can't set headers after they are sent.
    at validateHeader (_http_outgoing.js:489:11)
    at ServerResponse.setHeader (_http_outgoing.js:496:3)
    at ServerResponse.header (/Users/kmidkiff/WebstormProjects/servicebot/node_modules/express/lib/response.js:767:10)
    at ServerResponse.send (/Users/kmidkiff/WebstormProjects/servicebot/node_modules/express/lib/response.js:170:12)
    at ServerResponse.json (/Users/kmidkiff/WebstormProjects/servicebot/node_modules/express/lib/response.js:267:15)
    at /Users/kmidkiff/WebstormProjects/servicebot/plugins/api-gateway/app.js:203:43
    at Layer.handle_error (/Users/kmidkiff/WebstormProjects/servicebot/node_modules/express/lib/router/layer.js:71:5)
    at trim_prefix (/Users/kmidkiff/WebstormProjects/servicebot/node_modules/express/lib/router/index.js:315:13)
    at /Users/kmidkiff/WebstormProjects/servicebot/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/kmidkiff/WebstormProjects/servicebot/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/kmidkiff/WebstormProjects/servicebot/node_modules/express/lib/router/index.js:275:10)
    at /Users/kmidkiff/WebstormProjects/servicebot/plugins/api-gateway/app.js:187:13
    at Layer.handle [as handle_request] (/Users/kmidkiff/WebstormProjects/servicebot/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/kmidkiff/WebstormProjects/servicebot/node_modules/express/lib/router/index.js:317:13)
    at /Users/kmidkiff/WebstormProjects/servicebot/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/kmidkiff/WebstormProjects/servicebot/node_modules/express/lib/router/index.js:335:12)
    at Immediate.next (/Users/kmidkiff/WebstormProjects/servicebot/node_modules/express/lib/router/index.js:275:10)
    at Immediate._onImmediate (/Users/kmidkiff/WebstormProjects/servicebot/node_modules/express/lib/router/index.js:635:15)
    at runCallback (timers.js:783:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)
set cookie
Valid Request!
<img width="949" alt="screen shot 2017-10-22 at 2 41 41 pm" src="https://user-images.githubusercontent.com/6853957/31865116-2a62d782-b737-11e7-8e54-84a19912489f.png">

**Comment by bsears90** [comment]
is the something that can be replicated?

**Comment by darafsheh** [comment]
How do you replicate this Kevin?

**Comment by kmidkiff** [comment]
dono, just found it in my logs. All i know is what I saw from the log that it was during a POST to /api/v1/service-instances/3/add-charge
