### ISSUE TITLE
(not an issue) installation help

### ISSUE THREAD

**Issue by gautamz07** [service-bot/servicebot#369]
Hey guys how do i install this locally and just run it , preferably without docker , i believe i would need.

- postgres for the database 
- a stripe a/c

How do i go about running this locally , just to hack at it ? so far i've cloned the project and run `rpm install`.

**Comment by nivalamata** [comment]
Like wise I am struggling  to do the same thing,
steps that I tried, after cloning repository locally
1. install stable version of node js
2. install postgresql db
3. create a postgresql user with user name and password.
4. create a postgresql database named servicebot
5. in a root directory of repository I created a folder named env, in it I add a file .env with the following 
parameters

ADMIN_USER=admin
ADMIN_PASSWORD=guest
ADMIN_NAME=admin
VIRTUAL_HOST=servicebot.host


POSTGRES_DB_HOST=localhost
POSTGRES_DB_USER=put are postgresql user name
POSTGRES_DB_NAME=servicebot
POSTGRES_DB_PASSWORD=put ur postgresql. user password
POSTGRES_DB_PORT=5432

6. npm install
7. npm run-script build


but when I ran step number 7 I got this error


   ERROR in ./views/index.jsx
    Module build failed: SyntaxError: 'import' and 'export' may only appear at the top level (6:0)
      4 | (function() {
      5 |
    > 6 | import React from 'react';
        | ^
      7 | import {render} from 'react-dom';
      8 | import AppRouter from "./router.jsx";
      9 | import { AppContainer } from 'react-hot-loader'

     @ multi react-hot-loader/patch ./views/index.jsx

Any ideas how to solve this ..!!!!

**Comment by mylastore** [comment]
same here, not sure why we need docker

**Comment by mylastore** [comment]
@nivalamata just:  run npm run fullStart
Is working for me, but it needs the SSL to connect to Srtipe.

**Comment by gautamz07** [comment]
Do we need docker to run this project ?

**Comment by shakir-uz-zaman** [comment]
> @nivalamata just: run npm run fullStart
> Is working for me, but it needs the SSL to connect to Srtipe.

I am getting an error like this after following your instruction ,
CLOSIN DOWN THE SETUP!
redux-saga error: uncaught
at _callee
 at pluginSaga
 at bound enable
 at run
 TimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
    at Timeout._onTimeout (E:\Billing System\servicebot\node_modules\knex\lib\client.js:287:18)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)

How did you solve it ?

**Comment by Kristijan994** [comment]
Hello, does anyone have a **solution** on how to run the project **without docker?**
I've setup the **posgreSQL DB** and i'm facing the following error. Actually **gets stuck** after the identification of the environment file.

`DB EMPTY
starting setup
Configuration pre-set, initialization starting
env exists`

I've also tried to login on the psql DB with terminal just to check if the credentials are right and to make sure if i'm providing the right credentials in the .env file too, and it worked.

**Any solutions?**

**Comment by shakir-uz-zaman** [comment]
> Hello, does anyone have a **solution** on how to run the project **without docker?**
> I've setup the **posgreSQL DB** and i'm facing the following error. Actually **gets stuck** after the identification of the environment file.
> 
> `DB EMPTY starting setup Configuration pre-set, initialization starting env exists`
> 
> I've also tried to login on the psql DB with terminal just to check if the credentials are right and to make sure if i'm providing the right credentials in the .env file too, and it worked.
> 
> **Any solutions?**

Recently i installed this on my windows laptop without docker.

**Comment by Kristijan994** [comment]
> > Hello, does anyone have a **solution** on how to run the project **without docker?**
> > I've setup the **posgreSQL DB** and i'm facing the following error. Actually **gets stuck** after the identification of the environment file.
> > `DB EMPTY starting setup Configuration pre-set, initialization starting env exists`
> > I've also tried to login on the psql DB with terminal just to check if the credentials are right and to make sure if i'm providing the right credentials in the .env file too, and it worked.
> > **Any solutions?**
> 
> Recently i installed this on my windows laptop without docker.

Can you share your **installation steps** and/or share your **.env** file?

**Comment by shakir-uz-zaman** [comment]
@Kristijan994 
```
POSTGRES_DB_HOST=127.0.0.1
POSTGRES_DB_USER=postgres
POSTGRES_DB_NAME=api
POSTGRES_DB_PASSWORD=123
POSTGRES_DB_PORT=5432
SMTP_HOST=undefined
SMTP_USER=undefined
SMTP_PASSWORD=undefined
SMTP_PORT=undefined
INSTANCE_SALT=fe7316ec7d1e0994320ceb09849039c212bfe7724a48afa815b685d625c5
SECRET_KEY=4f3cfbc1688e03d3518fb04462ef3d23f176382541d9b3a519b381454f690867
```
this is the .env file. Actually this .env file will be automatically created , Yo have to setup some information to others configure files first. I installed this project locally without docker.
