### ISSUE TITLE
Servicebot won't launch with SSL certificate

### ISSUE THREAD

**Issue by FredFredrickson** [service-bot/servicebot#401]
I have a key, crt, and bundle file named as such:

Keyfile : servicebot.key
Certificate : servicebot.crt
CA : servicebot_bundle.crt

I downloaded the cert from ssls.com

Put all 3 files in /etc/ssl

Edited docker-compose.yaml:

servicebot:
   image: servicebot/servicebot
   environment:
      CERTIFICATES: "./ssl/"
      POSTGRES_DB_PORT : "5432"
      POSTGRES_DB_HOST : "db"
      POSTGRES_DB_USER : "servicebot_u"
      POSTGRES_DB_PASSWORD : "secret_doggo"
      POSTGRES_DB_NAME : "sb_db"
      SMTP_HOST : 'mail.editeddomain.com'
      SMTP_USER : 'billing@editeddomain.com'
      SMTP_PASSWORD : 'editedpassword'
      SMTP_PORT : '465'
      PORT : "3000"
    volumes:
      - upload-data:/usr/src/app/uploads
      - environment-file:/usr/src/app/env
      - /etc/ssl:/usr/src/app/ssl

But it won't launch. Launches fine if you comment out the 2 ssl lines and restart it on http but no https.

Logs:

`HOST DETECTED ON PORT 5432

> servicebot@0.9.11 start /usr/src/app
> node ./bin/start

CLOSIN DOWN THE SETUP!
redux-saga error: uncaught
at _callee
 at pluginSaga
 at bound enable
 at run
 Error: error:0909006C:PEM routines:get_name:no start line
    at Object.createSecureContext (_tls_common.js:149:17)
    at Server.setSecureContext (_tls_wrap.js:1294:27)
    at Server (_tls_wrap.js:1158:8)
    at new Server (https.js:64:14)
    at Object.createServer (https.js:88:10)
    at module.exports (/usr/src/app/plugins/api-gateway/server.js:13:29)
    at run (/usr/src/app/plugins/api-gateway/app.js:48:23)
    at run.next (<anonymous>)
    at next (/usr/src/app/node_modules/redux-saga/lib/internal/proc.js:313:27)
    at proc (/usr/src/app/node_modules/redux-saga/lib/internal/proc.js:272:3)
    at runForkEffect (/usr/src/app/node_modules/redux-saga/lib/internal/proc.js:555:19)
    at runEffect (/usr/src/app/node_modules/redux-saga/lib/internal/proc.js:436:544)
    at next (/usr/src/app/node_modules/redux-saga/lib/internal/proc.js:317:9)
    at currCb (/usr/src/app/node_modules/redux-saga/lib/internal/proc.js:389:7)
    at /usr/src/app/node_modules/redux-saga/lib/internal/proc.js:500:16
    at exec (/usr/src/app/node_modules/redux-saga/lib/internal/scheduler.js:25:5)
`

**Comment by FredFredrickson** [comment]
Ah- Figured it out. Malformed KEY file using copy-paste. Make sure you transfer your files in ascii not binary.
